from __future__ import annotations
from abc import ABC, abstractmethod


class NavigationAdapter(ABC):
    @abstractmethod
    def navigate_to(self, target_region: str, target_pose: tuple[float, float, float]) -> bool: ...
    @abstractmethod
    def cancel_navigation(self) -> None: ...
    @abstractmethod
    def get_pose(self) -> tuple[float, float, float]: ...
    @abstractmethod
    def get_distance_to_target(self) -> float: ...
    @abstractmethod
    def is_arrived(self) -> bool: ...
    @abstractmethod
    def is_localization_ok(self) -> bool: ...
    @abstractmethod
    def is_reachable(self, target_region: str) -> bool: ...


class PurificationAdapter(ABC):
    @abstractmethod
    def set_fan_level(self, level: int) -> None: ...
    @abstractmethod
    def start_purification(self) -> None: ...
    @abstractmethod
    def stop_purification(self) -> None: ...
    @abstractmethod
    def get_fan_state(self) -> dict: ...
    @abstractmethod
    def is_fan_healthy(self) -> bool: ...
