#!/usr/bin/env python3
from __future__ import annotations
import argparse
import json
import math
import pandas as pd
import numpy as np
from scripts._paths import add_root_argument, resolve_cli_root
from air_governance.common.config import load_yaml
from air_governance.simulation.environment import IndoorEnvironmentSimulator
from air_governance.simulation.scenarios import SCENARIOS


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description='Generate the existing simulation dataset format.')
    add_root_argument(parser)
    args = parser.parse_args(argv)
    root = resolve_cli_root(args)
    sys_cfg = load_yaml('config/system.yaml')
    sim_cfg = load_yaml('config/simulation.yaml')
    rank_cfg = load_yaml('config/ranker.yaml')
    seed0 = int(sys_cfg['random_seed'])
    env_rows, gt_rows = [], []
    episodes = []
    regions = list(sys_cfg['regions'])
    ep_count = int(sim_cfg['episodes_per_scenario'])
    steps = int(sim_cfg['steps_per_episode'])
    horizon_steps = int(rank_cfg['utility']['horizon_seconds']) // int(sim_cfg['sample_interval_seconds'])

    for s_idx, scenario_id in enumerate(SCENARIOS):
        for ep in range(ep_count):
            seed = seed0 + s_idx * 1000 + ep
            episode_id = f'{scenario_id}_ep{ep:02d}'
            sim = IndoorEnvironmentSimulator(scenario_id, seed=seed)
            robot_region = regions[ep % len(regions)]
            battery = 94.0 - ep * 0.7
            episodes.append({'episode_id': episode_id, 'scenario_id': scenario_id, 'seed': seed})
            waiting = {r: 0.0 for r in regions}

            for step in range(steps):
                decision_id = f'{episode_id}_d{step:03d}' if step >= 12 and step % 3 == 0 else ''
                samples = sim.samples(episode_id, robot_region=robot_region, battery_soc=battery,
                                      decision_id=decision_id)
                for sample in samples:
                    row = sample.to_dict(); row['step_index'] = step
                    env_rows.append(row)

                if decision_id:
                    rxy = sys_cfg['regions'][robot_region]
                    gains = {rid: sim.counterfactual_risk_gain(rid, horizon_steps=horizon_steps, fan_level=3) for rid in regions}
                    for rid in regions:
                        loc = sys_cfg['regions'][rid]
                        dist = math.hypot(float(rxy['x']) - float(loc['x']), float(rxy['y']) - float(loc['y']))
                        move_time = dist / 0.45
                        energy = 0.12 * dist + 0.02 * move_time
                        gt_rows.append({
                            'decision_id': decision_id, 'episode_id': episode_id, 'scenario_id': scenario_id,
                            'step_index': step, 'timestamp': sim.current_time.isoformat(), 'region_id': rid,
                            'robot_region': robot_region, 'battery_soc': battery,
                            'distance': dist, 'estimated_move_time': move_time, 'estimated_energy': energy,
                            'switch_cost': 0.0 if robot_region == rid else 1.0,
                            'scene_weight': 1.0, 'reachable': 1,
                            'counterfactual_risk_gain': gains[rid],
                        })
                    # Move the virtual decision origin to diversify response costs; no purification is applied here.
                    robot_region = regions[(regions.index(robot_region) + 1 + (step // 3) % 2) % len(regions)]
                battery = max(20.0, battery - 0.08)
                sim.step()

    out = root / 'data' / 'simulation'
    out.mkdir(parents=True, exist_ok=True)
    env = pd.DataFrame(env_rows)
    gt = pd.DataFrame(gt_rows)
    env.to_csv(out / 'env_samples.csv', index=False)
    gt.to_csv(out / 'candidate_ground_truth.csv', index=False)
    manifest = {
        'dataset_version': 'simulation_v1', 'source_type': 'SIMULATION',
        'random_seed': seed0, 'scenarios': list(SCENARIOS), 'episodes': episodes,
        'n_env_samples': int(len(env)), 'n_candidate_rows': int(len(gt)),
        'note': 'All records in this directory are generated by IndoorEnvironmentSimulator and are not real robot measurements.'
    }
    (out / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f'generated env_samples={len(env)} candidate_ground_truth={len(gt)}')

if __name__ == '__main__':
    main()
